/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description The process is up. It touches nothing: no database, no provider.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description The process is up. It touches nothing: no database, no provider.
     */
    get: operations["health_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Ready
     * @description Ready to serve: not shutting down and, with PostgreSQL, the database answers a minimal
     *     query. A status word only; never a host, a role, a version or a setting.
     */
    get: operations["health_ready_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/agent/turns": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Agent Turn
     * @description One conversational turn. Idempotent per `client_turn_id` while the API process retains
     *     the conversation. The assistant can only read and prepare a review; it cannot book.
     */
    post: operations["create_agent_turn_v1_agent_turns_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/appointment-proposals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Appointment Proposal
     * @description Describe what booking this slot would do. Nothing is saved.
     */
    post: operations["create_appointment_proposal_v1_appointment_proposals_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/appointments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm Appointment Route
     * @description The only write. Requires a valid proposal token and an explicit `confirm: true`.
     */
    post: operations["confirm_appointment_route_v1_appointments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/appointments/{appointment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Appointment */
    get: operations["read_appointment_v1_appointments__appointment_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/business": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Business */
    get: operations["read_business_v1_business_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/services": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Services */
    get: operations["list_services_v1_services_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/services/{service_id}/availability": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Availability */
    get: operations["read_availability_v1_services__service_id__availability_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/speech/transcriptions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Transcription
     * @description Transcribe one short recording. It does not call the assistant and stores nothing.
     */
    post: operations["create_transcription_v1_speech_transcriptions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AgentReply */
    AgentReply: {
      /**
       * Source
       * @enum {string}
       */
      source: "assistant" | "system";
      /** Text */
      text: string;
    };
    /** AgentTurnRequest */
    AgentTurnRequest: {
      /**
       * Client Turn Id
       * Format: uuid
       * @description Idempotency key: one per user submission.
       */
      client_turn_id: string;
      /**
       * Conversation Id
       * Format: uuid
       * @description Generated by the client for a new conversation.
       */
      conversation_id: string;
      /**
       * Message
       * @description What the visitor typed, 1 to 500 characters.
       */
      message: string;
      /**
       * Turn Index
       * @description 1-based position of this turn.
       */
      turn_index: number;
    };
    /**
     * AgentTurnResponse
     * @description Everything the visitor sees for one turn. Cached verbatim for idempotent retries.
     */
    AgentTurnResponse: {
      /** @description A prepared, unconfirmed review. Nothing is booked until the visitor confirms. */
      booking_review:
        components["schemas"]["AppointmentProposalResponse"] | null;
      /**
       * Client Turn Id
       * Format: uuid
       */
      client_turn_id: string;
      /**
       * Conversation Id
       * Format: uuid
       */
      conversation_id: string;
      /** Events */
      events: (
        | components["schemas"]["UserMessageEvent"]
        | components["schemas"]["ToolRequestedEvent"]
        | components["schemas"]["ToolResultEvent"]
        | components["schemas"]["BookingReviewReadyEvent"]
        | components["schemas"]["BookingReviewDiscardedEvent"]
        | components["schemas"]["AssistantMessageEvent"]
        | components["schemas"]["SystemMessageEvent"]
        | components["schemas"]["GuardrailEvent"]
        | components["schemas"]["ProviderErrorEvent"]
        | components["schemas"]["TurnErrorEvent"]
      )[];
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "completed" | "degraded";
      reply: components["schemas"]["AgentReply"];
      /** Turn Index */
      turn_index: number;
    };
    /** AppointmentProposalRequest */
    AppointmentProposalRequest: {
      /** Service Id */
      service_id: string;
      /**
       * Start
       * Format: date-time
       * @description Requested slot start. Must include a UTC offset.
       */
      start: string;
    };
    /**
     * AppointmentProposalResponse
     * @description What confirming would book. Nothing has been saved yet.
     */
    AppointmentProposalResponse: {
      /**
       * Customer Alias
       * @description Fictional demo name the server assigned.
       */
      customer_alias: string;
      /**
       * End
       * Format: date-time
       * @description End, UTC. Computed by the server.
       */
      end: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /**
       * Proposal Token
       * @description Signed, short-lived. Send it back to confirm.
       */
      proposal_token: string;
      service: components["schemas"]["ServiceResponse"];
      /**
       * Start
       * Format: date-time
       * @description Start, UTC.
       */
      start: string;
      /** Timezone */
      timezone: string;
    };
    /**
     * AppointmentResponse
     * @description What the schedule service confirmed and saved. Rendered from the saved row only.
     */
    AppointmentResponse: {
      /** Bench */
      bench: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Customer Alias */
      customer_alias: string;
      /**
       * End
       * Format: date-time
       * @description End, UTC.
       */
      end: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      service: components["schemas"]["AppointmentServiceResponse"];
      /** Source */
      source: string;
      /**
       * Start
       * Format: date-time
       * @description Start, UTC.
       */
      start: string;
      /**
       * Status
       * @enum {string}
       */
      status: "confirmed" | "cancelled";
      /** Timezone */
      timezone: string;
    };
    /**
     * AppointmentServiceResponse
     * @description The service as it was when the appointment was booked (a saved snapshot).
     */
    AppointmentServiceResponse: {
      /** Duration Minutes */
      duration_minutes: number;
      /** Id */
      id: string;
      /** Name */
      name: string;
      price: components["schemas"]["MoneyResponse"];
    };
    /** AssistantMessageEvent */
    AssistantMessageEvent: {
      /**
       * Actor
       * @constant
       */
      actor: "assistant";
      /**
       * At
       * Format: date-time
       */
      at: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "assistant_message";
      /**
       * Seq
       * @description Position within this turn, from 1.
       */
      seq: number;
      /** Text */
      text: string;
    };
    /** AvailabilityResponse */
    AvailabilityResponse: {
      /**
       * Date
       * Format: date
       * @description The requested date, interpreted in the business timezone.
       */
      date: string;
      /** Service Id */
      service_id: string;
      /** Slots */
      slots: components["schemas"]["SlotResponse"][];
      /** Timezone */
      timezone: string;
    };
    /**
     * BookingReviewDiscardedEvent
     * @description The review waiting for the visitor was withdrawn or replaced, so it can no longer be
     *     confirmed. Withdrawing books and cancels nothing: a review is only a proposal.
     */
    BookingReviewDiscardedEvent: {
      /**
       * Actor
       * @constant
       */
      actor: "tool";
      /**
       * At
       * Format: date-time
       */
      at: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "booking_review_discarded";
      /** Local Date */
      local_date: string;
      /** Local Start */
      local_start: string;
      /**
       * Reason
       * @enum {string}
       */
      reason: "declined" | "changed_search" | "replaced";
      /**
       * Seq
       * @description Position within this turn, from 1.
       */
      seq: number;
      /** Service Name */
      service_name: string;
    };
    /** BookingReviewReadyEvent */
    BookingReviewReadyEvent: {
      /**
       * Actor
       * @constant
       */
      actor: "tool";
      /**
       * At
       * Format: date-time
       */
      at: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "booking_review_ready";
      /** Local Date */
      local_date: string;
      /** Local End */
      local_end: string;
      /** Local Start */
      local_start: string;
      /** Price Display */
      price_display: string;
      /**
       * Seq
       * @description Position within this turn, from 1.
       */
      seq: number;
      /** Service Name */
      service_name: string;
      /** Timezone */
      timezone: string;
    };
    /** BookingWindowResponse */
    BookingWindowResponse: {
      /**
       * First Date
       * Format: date
       * @description First bookable date in the business timezone.
       */
      first_date: string;
      /**
       * Last Date
       * Format: date
       * @description Last bookable date in the business timezone.
       */
      last_date: string;
    };
    /** BusinessResponse */
    BusinessResponse: {
      /** Address */
      address: string;
      booking_window: components["schemas"]["BookingWindowResponse"];
      /** Currency */
      currency: string;
      /** Hours */
      hours: components["schemas"]["OpeningIntervalResponse"][];
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Phone */
      phone: string;
      /** Slot Interval Minutes */
      slot_interval_minutes: number;
      /** Tagline */
      tagline: string;
      /**
       * Timezone
       * @description IANA timezone of the business.
       */
      timezone: string;
    };
    /** ConfirmAppointmentRequest */
    ConfirmAppointmentRequest: {
      /**
       * Confirm
       * @description Must be true: the user explicitly confirmed.
       * @constant
       */
      confirm: true;
      /** Proposal Token */
      proposal_token: string;
    };
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string;
      /** Details */
      details?: components["schemas"]["ErrorFieldDetail"][] | null;
      /** Message */
      message: string;
    };
    /** ErrorFieldDetail */
    ErrorFieldDetail: {
      /**
       * Issue
       * @description Machine-readable validation issue type.
       */
      issue: string;
      /**
       * Loc
       * @description Location of the invalid field.
       */
      loc: string[];
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    /** GuardrailEvent */
    GuardrailEvent: {
      /**
       * Actor
       * @constant
       */
      actor: "system";
      /**
       * At
       * Format: date-time
       */
      at: string;
      /**
       * Code
       * @enum {string}
       */
      code:
        | "tool_not_allowed"
        | "invalid_tool_input"
        | "tool_budget_exceeded"
        | "model_call_budget_exceeded";
      /** Issues */
      issues: string[];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "guardrail";
      /**
       * Seq
       * @description Position within this turn, from 1.
       */
      seq: number;
      /** Tool */
      tool: string | null;
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /** MoneyResponse */
    MoneyResponse: {
      /**
       * Amount Minor
       * @description Amount in the currency's minor unit (e.g. cents).
       */
      amount_minor: number;
      /**
       * Currency
       * @description ISO 4217 currency code.
       */
      currency: string;
    };
    /** OpeningIntervalResponse */
    OpeningIntervalResponse: {
      /**
       * End
       * @description Local closing time, HH:MM.
       */
      end: string;
      /**
       * Start
       * @description Local opening time, HH:MM.
       */
      start: string;
      /**
       * Weekday
       * @description 0 = Monday ... 6 = Sunday.
       */
      weekday: number;
    };
    /** ProviderErrorEvent */
    ProviderErrorEvent: {
      /**
       * Actor
       * @constant
       */
      actor: "system";
      /**
       * At
       * Format: date-time
       */
      at: string;
      /**
       * Code
       * @enum {string}
       */
      code:
        | "model_timeout"
        | "model_rate_limited"
        | "model_unavailable"
        | "model_bad_output";
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "provider_error";
      /**
       * Seq
       * @description Position within this turn, from 1.
       */
      seq: number;
    };
    /**
     * ReadinessResponse
     * @description Only a status word: no host, version, role or configuration.
     */
    ReadinessResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: "ready" | "draining" | "unavailable";
    };
    /** ServiceResponse */
    ServiceResponse: {
      /** Description */
      description: string;
      /** Duration Minutes */
      duration_minutes: number;
      /** Id */
      id: string;
      /** Name */
      name: string;
      price: components["schemas"]["MoneyResponse"];
    };
    /** ServicesResponse */
    ServicesResponse: {
      /** Services */
      services: components["schemas"]["ServiceResponse"][];
    };
    /** SlotResponse */
    SlotResponse: {
      /**
       * End
       * Format: date-time
       * @description Slot end, UTC.
       */
      end: string;
      /**
       * Start
       * Format: date-time
       * @description Slot start, UTC.
       */
      start: string;
    };
    /** SystemMessageEvent */
    SystemMessageEvent: {
      /**
       * Actor
       * @constant
       */
      actor: "system";
      /**
       * At
       * Format: date-time
       */
      at: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "system_message";
      /**
       * Seq
       * @description Position within this turn, from 1.
       */
      seq: number;
      /** Text */
      text: string;
    };
    /**
     * ToolInput
     * @description Validated, allow-listed tool arguments. Only fields the model supplied are set.
     */
    ToolInput: {
      /** Date */
      date?: string | null;
      /** Days */
      days?: number | null;
      /** Earliest Local Time */
      earliest_local_time?: string | null;
      /** Latest Local Time */
      latest_local_time?: string | null;
      /** Service Id */
      service_id?: string | null;
      /** Slot Id */
      slot_id?: string | null;
    };
    /** ToolRequestedEvent */
    ToolRequestedEvent: {
      /**
       * Actor
       * @constant
       */
      actor: "assistant";
      /**
       * At
       * Format: date-time
       */
      at: string;
      input: components["schemas"]["ToolInput"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "tool_requested";
      /**
       * Seq
       * @description Position within this turn, from 1.
       */
      seq: number;
      /** Tool */
      tool: string;
    };
    /** ToolResultEvent */
    ToolResultEvent: {
      /**
       * Actor
       * @constant
       */
      actor: "tool";
      /**
       * At
       * Format: date-time
       */
      at: string;
      /** Code */
      code: string | null;
      /** Duration Ms */
      duration_ms: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "tool_result";
      /**
       * Seq
       * @description Position within this turn, from 1.
       */
      seq: number;
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "rejected" | "error";
      /** Summary */
      summary: string;
      /** Tool */
      tool: string;
    };
    /** TranscriptionResponse */
    TranscriptionResponse: {
      /**
       * Language
       * @description Transcription is English only for now.
       * @constant
       */
      language: "en";
      /**
       * Text
       * @description Machine-transcribed text. The visitor can edit it before sending it.
       */
      text: string;
    };
    /** TurnErrorEvent */
    TurnErrorEvent: {
      /**
       * Actor
       * @constant
       */
      actor: "system";
      /**
       * At
       * Format: date-time
       */
      at: string;
      /**
       * Code
       * @enum {string}
       */
      code: "turn_deadline_exceeded" | "storage_unavailable" | "internal_error";
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "turn_error";
      /**
       * Seq
       * @description Position within this turn, from 1.
       */
      seq: number;
    };
    /** UserMessageEvent */
    UserMessageEvent: {
      /**
       * Actor
       * @constant
       */
      actor: "user";
      /**
       * At
       * Format: date-time
       */
      at: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "user_message";
      /**
       * Seq
       * @description Position within this turn, from 1.
       */
      seq: number;
      /** Text */
      text: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  health_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  health_ready_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
      /** @description Not ready, or draining. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
    };
  };
  create_agent_turn_v1_agent_turns_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgentTurnRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentTurnResponse"];
        };
      };
      /** @description conversation_not_found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description idempotency_key_reused, turn_in_progress, conversation_busy, turn_out_of_order or conversation_limit_reached. Nothing was accepted. `turn_in_progress` and `conversation_busy` send Retry-After. */
      409: {
        headers: {
          /** @description Seconds to wait before retrying (turn_in_progress, busy). */
          "Retry-After"?: number;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description conversation_expired. */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description validation_error. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description agent_busy. */
      429: {
        headers: {
          /** @description Seconds to wait before retrying. */
          "Retry-After"?: number;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description agent_unavailable (no provider is configured), demo_budget_reached (today's allowance is used up), budget_unavailable (the budget could not be checked) or service_draining (the process is shutting down). The provider was not called. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_appointment_proposal_v1_appointment_proposals_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AppointmentProposalRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AppointmentProposalResponse"];
        };
      };
      /** @description Unknown service. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description slot_unavailable: every bench is taken. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description validation_error, date_out_of_range or slot_not_offered. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirm_appointment_route_v1_appointments_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmAppointmentRequest"];
      };
    };
    responses: {
      /** @description The proposal had already been confirmed: the original appointment. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AppointmentResponse"];
        };
      };
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AppointmentResponse"];
        };
      };
      /** @description slot_unavailable (just taken), proposal_stale (details changed) or proposal_discarded (the visitor withdrew this review: nothing is booked). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description validation_error, proposal_invalid, proposal_expired, or slot_not_offered (the time is no longer offered, for example it is now inside the lead time). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  read_appointment_v1_appointments__appointment_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        appointment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AppointmentResponse"];
        };
      };
      /** @description Unknown appointment. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid appointment id. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  read_business_v1_business_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BusinessResponse"];
        };
      };
      /** @description Storage unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_services_v1_services_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServicesResponse"];
        };
      };
      /** @description Storage unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  read_availability_v1_services__service_id__availability_get: {
    parameters: {
      query: {
        /** @description Local date in the business timezone (YYYY-MM-DD). */
        date: string;
      };
      header?: never;
      path: {
        service_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvailabilityResponse"];
        };
      };
      /** @description Unknown service. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid request or date outside the window. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_transcription_v1_speech_transcriptions_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description What the client says the recording lasts. Not verified by the server: diagnostics only. */
        "X-Audio-Duration-Ms"?: number | null;
      };
      path?: never;
      cookie?: never;
    };
    /** @description The raw audio bytes of one short recording (at most 256 KB). */
    requestBody: {
      content: {
        "audio/mp4": string;
        "audio/ogg": string;
        "audio/wav": string;
        "audio/webm": string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TranscriptionResponse"];
        };
      };
      /** @description audio_too_large: more than 256 KB. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description audio_unsupported: type not allowed, or the signature does not match it. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description audio_invalid, no_speech or validation_error. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description speech_busy: every transcription slot is taken. */
      429: {
        headers: {
          /** @description Seconds to wait before retrying. */
          "Retry-After"?: number;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description transcription_failed. */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description speech_unavailable (no provider is configured), demo_budget_reached, budget_unavailable or service_draining. The provider was not called. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description transcription_timeout. */
      504: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
