/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/business": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Business */
    get: operations["read_business_v1_business_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/services": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Services */
    get: operations["list_services_v1_services_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/services/{service_id}/availability": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Availability */
    get: operations["read_availability_v1_services__service_id__availability_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AvailabilityResponse */
    AvailabilityResponse: {
      /**
       * Date
       * Format: date
       * @description The requested date, interpreted in the business timezone.
       */
      date: string;
      /** Service Id */
      service_id: string;
      /** Slots */
      slots: components["schemas"]["SlotResponse"][];
      /** Timezone */
      timezone: string;
    };
    /** BookingWindowResponse */
    BookingWindowResponse: {
      /**
       * First Date
       * Format: date
       * @description First bookable date in the business timezone.
       */
      first_date: string;
      /**
       * Last Date
       * Format: date
       * @description Last bookable date in the business timezone.
       */
      last_date: string;
    };
    /** BusinessResponse */
    BusinessResponse: {
      /** Address */
      address: string;
      booking_window: components["schemas"]["BookingWindowResponse"];
      /** Currency */
      currency: string;
      /** Hours */
      hours: components["schemas"]["OpeningIntervalResponse"][];
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Phone */
      phone: string;
      /** Slot Interval Minutes */
      slot_interval_minutes: number;
      /** Tagline */
      tagline: string;
      /**
       * Timezone
       * @description IANA timezone of the business.
       */
      timezone: string;
    };
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string;
      /** Details */
      details?: components["schemas"]["ErrorFieldDetail"][] | null;
      /** Message */
      message: string;
    };
    /** ErrorFieldDetail */
    ErrorFieldDetail: {
      /**
       * Issue
       * @description Machine-readable validation issue type.
       */
      issue: string;
      /**
       * Loc
       * @description Location of the invalid field.
       */
      loc: string[];
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /** MoneyResponse */
    MoneyResponse: {
      /**
       * Amount Minor
       * @description Amount in the currency's minor unit (e.g. cents).
       */
      amount_minor: number;
      /**
       * Currency
       * @description ISO 4217 currency code.
       */
      currency: string;
    };
    /** OpeningIntervalResponse */
    OpeningIntervalResponse: {
      /**
       * End
       * @description Local closing time, HH:MM.
       */
      end: string;
      /**
       * Start
       * @description Local opening time, HH:MM.
       */
      start: string;
      /**
       * Weekday
       * @description 0 = Monday ... 6 = Sunday.
       */
      weekday: number;
    };
    /** ServiceResponse */
    ServiceResponse: {
      /** Description */
      description: string;
      /** Duration Minutes */
      duration_minutes: number;
      /** Id */
      id: string;
      /** Name */
      name: string;
      price: components["schemas"]["MoneyResponse"];
    };
    /** ServicesResponse */
    ServicesResponse: {
      /** Services */
      services: components["schemas"]["ServiceResponse"][];
    };
    /** SlotResponse */
    SlotResponse: {
      /**
       * End
       * Format: date-time
       * @description Slot end, UTC.
       */
      end: string;
      /**
       * Start
       * Format: date-time
       * @description Slot start, UTC.
       */
      start: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  read_business_v1_business_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BusinessResponse"];
        };
      };
    };
  };
  list_services_v1_services_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServicesResponse"];
        };
      };
    };
  };
  read_availability_v1_services__service_id__availability_get: {
    parameters: {
      query: {
        /** @description Local date in the business timezone (YYYY-MM-DD). */
        date: string;
      };
      header?: never;
      path: {
        service_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvailabilityResponse"];
        };
      };
      /** @description Unknown service. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid request or date outside the window. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
