"""Wire contract of `POST /v1/agent/turns` (frozen Pydantic models).

The proposal token appears only inside `booking_review`, because the browser must return it to
confirm. No event field can carry it: events are built by `EventLog` from sanitized values.
"""

import re
from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator, model_validator

from voice_agent_api.api.schemas import AppointmentProposalResponse

MAX_MESSAGE_CHARS = 500
MAX_TURNS = 30
_CONTROL = re.compile(r"[\x00-\x09\x0b-\x1f\x7f]")


class AgentTurnRequest(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    conversation_id: UUID = Field(description="Generated by the client for a new conversation.")
    client_turn_id: UUID = Field(description="Idempotency key: one per user submission.")
    turn_index: int = Field(ge=1, le=MAX_TURNS, description="1-based position of this turn.")
    message: str = Field(
        max_length=2000, description="What the visitor typed, 1 to 500 characters."
    )

    @field_validator("message")
    @classmethod
    def _normalize(cls, value: str) -> str:
        text = value.strip()
        if not text or len(text) > MAX_MESSAGE_CHARS:
            raise ValueError("Expected 1 to 500 characters.")
        if _CONTROL.search(text):
            raise ValueError("Control characters are not allowed.")
        return text


class _Event(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    seq: int = Field(description="Position within this turn, from 1.")
    at: AwareDatetime


class ToolInput(BaseModel):
    """Validated, allow-listed tool arguments. Only fields the model supplied are set."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    service_id: str | None = None
    date: str | None = None
    days: int | None = None
    earliest_local_time: str | None = None
    latest_local_time: str | None = None
    slot_id: str | None = None


class UserMessageEvent(_Event):
    kind: Literal["user_message"]
    actor: Literal["user"]
    text: str


class ToolRequestedEvent(_Event):
    kind: Literal["tool_requested"]
    actor: Literal["assistant"]
    tool: str
    input: ToolInput


class ToolResultEvent(_Event):
    kind: Literal["tool_result"]
    actor: Literal["tool"]
    tool: str
    status: Literal["ok", "rejected", "error"]
    duration_ms: int
    summary: str
    code: str | None


class BookingReviewReadyEvent(_Event):
    kind: Literal["booking_review_ready"]
    actor: Literal["tool"]
    service_name: str
    local_date: str
    local_start: str
    local_end: str
    timezone: str
    price_display: str


class BookingReviewDiscardedEvent(_Event):
    """The review waiting for the visitor was withdrawn or replaced, so it can no longer be
    confirmed. Withdrawing books and cancels nothing: a review is only a proposal."""

    kind: Literal["booking_review_discarded"]
    actor: Literal["tool"]
    reason: Literal["declined", "changed_search", "replaced"]
    service_name: str
    local_date: str
    local_start: str


class AssistantMessageEvent(_Event):
    kind: Literal["assistant_message"]
    actor: Literal["assistant"]
    text: str


class SystemMessageEvent(_Event):
    kind: Literal["system_message"]
    actor: Literal["system"]
    text: str


class GuardrailEvent(_Event):
    kind: Literal["guardrail"]
    actor: Literal["system"]
    code: Literal[
        "tool_not_allowed",
        "invalid_tool_input",
        "tool_budget_exceeded",
        "model_call_budget_exceeded",
    ]
    tool: str | None
    issues: list[str]


class ProviderErrorEvent(_Event):
    kind: Literal["provider_error"]
    actor: Literal["system"]
    code: Literal["model_timeout", "model_rate_limited", "model_unavailable", "model_bad_output"]


class TurnErrorEvent(_Event):
    kind: Literal["turn_error"]
    actor: Literal["system"]
    code: Literal["turn_deadline_exceeded", "storage_unavailable", "internal_error"]


TimelineEvent = Annotated[
    UserMessageEvent
    | ToolRequestedEvent
    | ToolResultEvent
    | BookingReviewReadyEvent
    | BookingReviewDiscardedEvent
    | AssistantMessageEvent
    | SystemMessageEvent
    | GuardrailEvent
    | ProviderErrorEvent
    | TurnErrorEvent,
    Field(discriminator="kind"),
]


class AgentReply(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    source: Literal["assistant", "system"]
    text: str


class AgentTurnResponse(BaseModel):
    """Everything the visitor sees for one turn. Cached verbatim for idempotent retries."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    conversation_id: UUID
    client_turn_id: UUID
    turn_index: int
    outcome: Literal["completed", "degraded"]
    reply: AgentReply
    events: list[TimelineEvent]
    booking_review: AppointmentProposalResponse | None = Field(
        description="A prepared, unconfirmed review. Nothing is booked until the visitor confirms."
    )

    @model_validator(mode="after")
    def _review_event_matches_review(self) -> "AgentTurnResponse":
        ready = sum(1 for event in self.events if event.kind == "booking_review_ready")
        if ready != (1 if self.booking_review is not None else 0):
            raise ValueError("booking_review_ready must match booking_review.")
        return self
